export enum ElementEnum {
    LOGIN_BUTTON_ACTION = "login-button-action",
    LOGIN_BUTTON_BLOCK = "login-button-block",
    JIRA_CREATE_MODAL = "jira-create-modal",
    JIRA_PROJECT_ACTION = "jira-project-action",
    JIRA_PROJECT_BLOCK = "jira-project-block",
    JIRA_ISSUE_TYPE_ACTION = "jira-issue-type-action",
    JIRA_ISSUE_TYPE_BLOCK = "jira-issue-type-block",
    JIRA_SUMMARY_ACTION = "jira-summary-action",
    JIRA_SUMMARY_BLOCK = "jira-summary-block",
    JIRA_DESCRIPTION_ACTION = "jira-description-action",
    JIRA_DESCRIPTION_BLOCK = "jira-description-block",
    JIRA_PRIORITY_ACTION = "jira-priority-action",
    JIRA_PRIORITY_BLOCK = "jira-priority-block",
    JIRA_ASSIGNEE_ACTION = "jira-assignee-action",
    JIRA_ASSIGNEE_BLOCK = "jira-assignee-block",
    JIRA_CREATE_ACTION = "jira-create-action",
}